name: scan
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: scan
    runs-on: windows-latest
    steps:
    - name: Run SonarCloud scanner
      uses: highbyte/sonarscan-dotnet@v2.1.3
      with:
        sonarProjectKey: logikfabrik_BuddyApiClient
        sonarProjectName:  BuddyApiClient
        sonarOrganization: logikfabrik
        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="src/*Test/coverage.opencover.xml" /v:"0.0.1.${{ github.run_number }}"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}